// Rules for eslint-plugin-unicorn
export default {
  // 'unicorn/catch-error-name': 'warn',
  // 'unicorn/consistent-destructuring': 'warn',
  'unicorn/consistent-empty-array-spread': 'warn',
  // 'unicorn/consistent-function-scoping': 'warn',
  'unicorn/consistent-optional-chaining': 'warn',
  'unicorn/custom-error-definition': 'warn',
  'unicorn/empty-brace-spaces': 'warn',
  'unicorn/error-message': 'warn',
  'unicorn/escape-case': 'warn',
  'unicorn/explicit-timer-delay': 'warn',
  // 'unicorn/expiring-todo-comments': 'warn',
  // 'unicorn/explicit-length-check': 'warn',
  // 'unicorn/filename-case': 'warn',
  'unicorn/import-style': 'warn',
  'unicorn/new-for-builtins': 'warn',
  'unicorn/no-accidental-bitwise-operator': 'warn',
  'unicorn/no-anonymous-default-export': 'warn',
  // 'unicorn/no-array-callback-reference': 'warn',
  'unicorn/no-array-fill-with-reference-type': 'warn',
  'unicorn/no-array-from-fill': 'warn',
  'unicorn/no-array-method-this-argument': 'warn',
  'unicorn/no-array-push-push': 'warn',
  'unicorn/no-array-sort-for-min-max': 'warn',
  'unicorn/no-await-expression-member': 'warn',
  'unicorn/no-await-in-promise-methods': 'warn',
  'unicorn/no-break-in-nested-loop': 'warn',
  'unicorn/no-chained-comparison': 'warn',
  'unicorn/no-collection-bracket-access': 'warn',
  // 'unicorn/no-computed-property-existence-check': 'warn',
  'unicorn/no-console-spaces': 'warn',
  'unicorn/no-declarations-before-early-exit': 'warn',
  'unicorn/no-document-cookie': 'warn',
  'unicorn/no-double-comparison': 'warn',
  'unicorn/no-duplicate-logical-operands': 'warn',
  'unicorn/no-duplicate-loops': 'warn',
  'unicorn/no-empty-file': 'warn',
  'unicorn/no-exports-in-scripts': 'warn',
  'unicorn/no-for-each': 'warn',
  'unicorn/no-for-loop': 'warn',
  // 'unicorn/no-hex-escape': 'warn',
  'unicorn/no-immediate-mutation': 'warn',
  'unicorn/no-incorrect-query-selector': 'warn',
  'unicorn/no-incorrect-template-string-interpolation': 'warn',
  'unicorn/no-instanceof-array': 'warn',
  'unicorn/no-invalid-character-comparison': 'warn',
  'unicorn/no-invalid-fetch-options': 'warn',
  'unicorn/no-invalid-remove-event-listener': 'warn',
  // 'unicorn/no-keyword-prefix': 'warn',
  'unicorn/no-late-current-target-access': 'warn',
  'unicorn/no-late-event-control': 'warn',
  'unicorn/no-lonely-if': 'warn',
  'unicorn/no-loop-iterable-mutation': 'warn',
  'unicorn/no-magic-array-flat-depth': 'warn',
  'unicorn/no-misrefactored-assignment': 'warn',
  // 'unicorn/no-negated-condition': 'warn',
  // 'unicorn/no-negation-in-equality-check': 'warn',
  'unicorn/no-nested-ternary': 'warn',
  'unicorn/no-new-array': 'warn',
  'unicorn/no-new-buffer': 'warn',
  'unicorn/no-non-function-verb-prefix': 'warn',
  'unicorn/no-nonstandard-builtin-properties': 'warn',
  // 'unicorn/no-null': 'warn',
  // 'unicorn/no-object-as-default-parameter': 'warn',

  'unicorn/no-process-exit': 'warn',
  'unicorn/no-redundant-comparison': 'warn',
  'unicorn/no-return-array-push': 'warn',
  'unicorn/no-selector-as-dom-name': 'warn',
  'unicorn/no-single-promise-in-promise-methods': 'warn',
  'unicorn/no-static-only-class': 'warn',
  'unicorn/no-subtraction-comparison': 'warn',
  // 'unicorn/no-thenable': 'warn',
  'unicorn/no-this-assignment': 'warn',
  // 'unicorn/no-typeof-undefined': 'warn',
  'unicorn/no-uncalled-method': 'warn',
  'unicorn/no-unnecessary-await': 'warn',
  'unicorn/no-unnecessary-boolean-comparison': 'warn',
  'unicorn/no-unnecessary-nested-ternary': 'warn',
  'unicorn/no-unnecessary-polyfills': 'warn',
  'unicorn/no-unreadable-array-destructuring': 'warn',
  'unicorn/no-unreadable-for-of-expression': 'warn',
  'unicorn/no-unreadable-iife': 'warn',
  'unicorn/no-unreadable-object-destructuring': 'warn',
  'unicorn/no-unsafe-property-key': 'warn',
  'unicorn/no-unused-array-method-return': 'warn',
  'unicorn/no-unused-properties': 'warn',
  'unicorn/no-useless-coercion': 'warn',
  'unicorn/no-useless-delete-check': 'warn',
  'unicorn/no-useless-else': 'warn',
  'unicorn/no-useless-fallback-in-spread': 'warn',
  'unicorn/no-useless-iterator-to-array': 'warn',
  'unicorn/no-useless-length-check': 'warn',
  'unicorn/no-useless-promise-resolve-reject': 'warn',
  'unicorn/no-useless-recursion': 'warn',
  'unicorn/no-useless-spread': 'warn',
  'unicorn/no-useless-switch-case': 'warn',
  'unicorn/no-useless-undefined': 'warn',
  'unicorn/no-zero-fractions': 'warn',
  'unicorn/number-literal-case': 'warn',
  // 'unicorn/numeric-separators-style': 'warn',
  // 'unicorn/prefer-abort-signal-any': 'warn', // TODO: Enable this rule
  'unicorn/prefer-abort-signal-timeout': 'warn',
  // 'unicorn/prefer-add-event-listener': 'warn',
  'unicorn/prefer-array-find': 'warn',
  'unicorn/prefer-array-flat': 'warn',
  'unicorn/prefer-array-flat-map': 'warn',
  'unicorn/prefer-array-from-map': 'warn',
  'unicorn/prefer-array-index-of': 'warn',
  'unicorn/prefer-array-iterable-methods': 'warn',
  'unicorn/prefer-array-last-methods': 'warn',
  'unicorn/prefer-array-some': 'warn',
  // 'unicorn/prefer-at': 'warn',
  'unicorn/prefer-blob-reading-methods': 'warn',
  'unicorn/prefer-boolean-return': 'warn',
  // 'unicorn/prefer-code-point': 'warn',
  'unicorn/prefer-date-now': 'warn',
  'unicorn/prefer-default-parameters': 'warn',
  'unicorn/prefer-direct-iteration': 'warn',
  // 'unicorn/prefer-dom-node-append': 'warn',
  'unicorn/dom-node-dataset': 'warn',
  // 'unicorn/prefer-dom-node-remove': 'warn',
  'unicorn/prefer-dom-node-text-content': 'warn',
  'unicorn/prefer-event-target': 'warn',
  // 'unicorn/prefer-export-from': 'warn',
  'unicorn/prefer-flat-math-min-max': 'warn',
  'unicorn/prefer-has-check': 'warn',
  'unicorn/prefer-hoisting-branch-code': 'warn',
  'unicorn/prefer-https': 'warn',
  'unicorn/prefer-includes': 'warn',
  'unicorn/prefer-includes-over-repeated-comparisons': 'warn',
  'unicorn/prefer-iterator-to-array-at-end': 'warn',
  'unicorn/prefer-json-parse-buffer': 'warn',
  'unicorn/prefer-keyboard-event-key': 'warn',
  'unicorn/prefer-logical-operator-over-ternary': 'warn',
  'unicorn/prefer-math-abs': 'warn',
  'unicorn/prefer-math-trunc': 'warn',
  'unicorn/prefer-math-min-max': 'warn',
  // 'unicorn/prefer-minimal-ternary': 'warn',
  // 'unicorn/prefer-modern-dom-apis': 'warn',
  'unicorn/prefer-modern-math-apis': 'warn',
  // 'unicorn/prefer-module': 'warn',
  'unicorn/prefer-native-coercion-functions': 'warn',
  'unicorn/prefer-negative-index': 'warn',
  'unicorn/prefer-node-protocol': 'warn',
  'unicorn/prefer-number-is-safe-integer': 'warn',
  // 'unicorn/prefer-number-properties': 'warn',
  'unicorn/prefer-object-destructuring-defaults': 'warn',
  'unicorn/prefer-object-from-entries': 'warn',
  'unicorn/prefer-observer-apis': 'warn',
  'unicorn/prefer-promise-try': 'warn',
  // 'unicorn/prefer-optional-catch-binding': 'warn',
  'unicorn/prefer-prototype-methods': 'warn',
  // 'unicorn/prefer-query-selector': 'warn',
  'unicorn/prefer-reflect-apply': 'warn',
  'unicorn/prefer-regexp-test': 'warn',
  'unicorn/prefer-set-has': 'warn',
  'unicorn/prefer-set-size': 'warn',
  'unicorn/prefer-simple-condition-first': 'warn',
  'unicorn/prefer-spread': 'warn',
  // 'unicorn/prefer-string-raw': 'warn',
  // 'unicorn/prefer-string-replace-all': 'warn',
  'unicorn/prefer-string-slice': 'warn',
  'unicorn/prefer-string-starts-ends-with': 'warn',
  'unicorn/prefer-string-trim-start-end': 'warn',
  'unicorn/prefer-structured-clone': 'warn',
  // 'unicorn/prefer-switch': 'warn',
  // 'unicorn/prefer-ternary': 'warn',
  // 'unicorn/prefer-top-level-await': 'warn',
  // 'unicorn/prefer-type-error': 'warn',
  // 'unicorn/prevent-abbreviations': 'warn',
  'unicorn/relative-url-style': 'warn',
  'unicorn/require-array-join-separator': 'warn',
  'unicorn/require-array-sort-compare': 'warn',
  'unicorn/require-number-to-fixed-digits-argument': 'warn',
  'unicorn/require-passive-events': 'warn',
  'unicorn/require-post-message-target-origin': 'warn',
  'unicorn/string-content': 'warn',
  // 'unicorn/switch-case-braces': 'warn',
  // 'unicorn/template-indent': 'warn',
  // 'unicorn/text-encoding-identifier-case': 'warn',
  'unicorn/throw-new-error': 'warn',
};
